server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=university;encrypt=false
    username: stefan
    password: pass
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    #database: mssql
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  main:
    web-application-type: servlet